CREATE TABLE `produits` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `nom` varchar(255) DEFAULT NULL,
  `description` text,
  `prix_ht_unitaire` decimal(3,2) DEFAULT 0,
  `tva` FLOAT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (1, 'Vanilla Beans', CONCAT('Description de notre produit ', nom), 3.36, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (2, 'Flour - Semolina', CONCAT('Description de notre produit ', nom), 3.61, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (3, 'Cheese - Valancey', CONCAT('Description de notre produit ', nom), 1.7, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (4, 'Coco', CONCAT('Description de notre produit ', nom), 2.47, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (5, 'Hinge W Undercut', CONCAT('Description de notre produit ', nom), 3.54, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (6, 'Shallots', CONCAT('Description de notre produit ', nom), 3.29, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (7, 'Cocoa Feuilletine', CONCAT('Description de notre produit ', nom), 2.66, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (8, 'Bread Foccacia Whole', CONCAT('Description de notre produit ', nom), 1.62, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (9, 'Limes', CONCAT('Description de notre produit ', nom), 2.09, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (10, 'Pears - Bartlett', CONCAT('Description de notre produit ', nom), 1.87, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (11, 'Mcguinness - Blue Curacao', CONCAT('Description de notre produit ', nom), 0.48, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (12, 'Cinnamon Buns Sticky', CONCAT('Description de notre produit ', nom), 2.87, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (13, 'Lamb Leg - Bone - In Nz', CONCAT('Description de notre produit ', nom), 1.97, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (14, 'Tea - Mint', CONCAT('Description de notre produit ', nom), 1.21, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (15, 'Lamb - Whole, Fresh', CONCAT('Description de notre produit ', nom), 0.86, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (16, 'Turnip - Mini', CONCAT('Description de notre produit ', nom), 3.66, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (17, 'Red Pepper Paste', CONCAT('Description de notre produit ', nom), 1.39, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (18, 'Parsnip', CONCAT('Description de notre produit ', nom), 2.56, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (19, 'Bread - Olive Dinner Roll', CONCAT('Description de notre produit ', nom), 0.12, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (20, 'Syrup - Golden, Lyles', CONCAT('Description de notre produit ', nom), 2.5, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (21, 'Bag - Regular Kraft 20 Lb', CONCAT('Description de notre produit ', nom), 1.36, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (22, 'Corn Shoots', CONCAT('Description de notre produit ', nom), 3.52, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (23, 'Cheese - Boursin, Garlic / Herbs', CONCAT('Description de notre produit ', nom), 0.65, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (24, 'Pumpkin', CONCAT('Description de notre produit ', nom), 3.92, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (25, 'Beer - Molson Excel', CONCAT('Description de notre produit ', nom), 1.21, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (26, 'Garlic - Elephant', CONCAT('Description de notre produit ', nom), 0.57, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (27, 'Sugar - Icing', CONCAT('Description de notre produit ', nom), 1.72, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (28, 'Wine - Riesling Dr. Pauly', CONCAT('Description de notre produit ', nom), 0.54, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (29, 'Grand Marnier', CONCAT('Description de notre produit ', nom), 3.23, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (30, 'Pork - Back, Long Cut, Boneless', CONCAT('Description de notre produit ', nom), 0.44, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (31, 'Whmis Spray Bottle Graduated', CONCAT('Description de notre produit ', nom), 0.79, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (32, 'Pastry - Banana Tea Loaf', CONCAT('Description de notre produit ', nom), 3.62, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (33, 'Creme De Banane - Marie', CONCAT('Description de notre produit ', nom), 3.53, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (34, 'Sauce - Plum', CONCAT('Description de notre produit ', nom), 3.32, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (35, 'Cheese - Oka', CONCAT('Description de notre produit ', nom), 0.32, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (36, 'Carbonated Water - Blackcherry', CONCAT('Description de notre produit ', nom), 2.66, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (37, 'Pork - Backs - Boneless', CONCAT('Description de notre produit ', nom), 2.31, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (38, 'Honey - Liquid', CONCAT('Description de notre produit ', nom), 3.59, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (39, 'Breakfast Quesadillas', CONCAT('Description de notre produit ', nom), 1.31, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (40, 'Towel Multifold', CONCAT('Description de notre produit ', nom), 0.51, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (41, 'Ecolab - Hobart Upr Prewash Arm', CONCAT('Description de notre produit ', nom), 1.2, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (42, 'Nantucket - Kiwi Berry Cktl.', CONCAT('Description de notre produit ', nom), 1.0, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (43, 'Sprite, Diet - 355ml', CONCAT('Description de notre produit ', nom), 3.22, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (44, 'Cloves - Whole', CONCAT('Description de notre produit ', nom), 3.38, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (45, 'Octopus', CONCAT('Description de notre produit ', nom), 2.41, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (46, 'Pie Filling - Pumpkin', CONCAT('Description de notre produit ', nom), 0.76, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (47, 'Cheese - Woolwich Goat, Log', CONCAT('Description de notre produit ', nom), 2.08, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (48, 'Flour - Strong', CONCAT('Description de notre produit ', nom), 0.62, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (49, 'Asparagus - White, Canned', CONCAT('Description de notre produit ', nom), 1.38, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (50, 'Lobster - Cooked', CONCAT('Description de notre produit ', nom), 2.24, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (51, 'Truffle Shells - White Chocolate', CONCAT('Description de notre produit ', nom), 2.68, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (52, 'Oysters - Smoked', CONCAT('Description de notre produit ', nom), 3.91, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (53, 'Pail - 15l White, With Handle', CONCAT('Description de notre produit ', nom), 0.33, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (54, 'Spice - Montreal Steak Spice', CONCAT('Description de notre produit ', nom), 2.61, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (55, 'Mushroom - King Eryingii', CONCAT('Description de notre produit ', nom), 0.38, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (56, 'Beets - Golden', CONCAT('Description de notre produit ', nom), 3.8, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (57, 'Cinnamon Buns Sticky', CONCAT('Description de notre produit ', nom), 3.14, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (58, 'Mangostein', CONCAT('Description de notre produit ', nom), 2.9, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (59, 'Steampan - Lid For Half Size', CONCAT('Description de notre produit ', nom), 2.25, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (60, 'Flower - Leather Leaf Fern', CONCAT('Description de notre produit ', nom), 0.1, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (61, 'Chicken - Leg / Back Attach', CONCAT('Description de notre produit ', nom), 2.65, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (62, 'Spinach - Packaged', CONCAT('Description de notre produit ', nom), 2.21, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (63, 'Pork - Chop, Frenched', CONCAT('Description de notre produit ', nom), 3.91, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (64, 'Lemon Tarts', CONCAT('Description de notre produit ', nom), 3.11, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (65, 'Fish - Scallops, Cold Smoked', CONCAT('Description de notre produit ', nom), 3.09, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (66, 'Beef - Kindney, Whole', CONCAT('Description de notre produit ', nom), 2.23, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (67, 'Pumpkin', CONCAT('Description de notre produit ', nom), 0.82, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (68, 'Chinese Foods - Thick Noodles', CONCAT('Description de notre produit ', nom), 2.29, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (69, 'Vinegar - Sherry', CONCAT('Description de notre produit ', nom), 1.37, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (70, 'Sauce - Cranberry', CONCAT('Description de notre produit ', nom), 0.75, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (71, 'Ecolab - Hobart Upr Prewash Arm', CONCAT('Description de notre produit ', nom), 0.64, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (72, 'Beef - Striploin Aa', CONCAT('Description de notre produit ', nom), 2.42, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (73, 'Swiss Chard - Red', CONCAT('Description de notre produit ', nom), 2.62, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (74, 'Mushroom - Porcini, Dry', CONCAT('Description de notre produit ', nom), 0.17, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (75, 'Extract - Almond', CONCAT('Description de notre produit ', nom), 1.96, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (76, 'Cabbage - Nappa', CONCAT('Description de notre produit ', nom), 0.77, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (77, 'Sea Bass - Fillets', CONCAT('Description de notre produit ', nom), 1.51, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (78, 'Ice Cream Bar - Hageen Daz To', CONCAT('Description de notre produit ', nom), 0.84, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (79, 'Cookie Trail Mix', CONCAT('Description de notre produit ', nom), 2.65, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (80, 'Bagel - Whole White Sesame', CONCAT('Description de notre produit ', nom), 1.64, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (81, 'Tart Shells - Savory, 2', CONCAT('Description de notre produit ', nom), 1.61, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (82, 'Cabbage - Green', CONCAT('Description de notre produit ', nom), 0.89, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (83, 'Table Cloth 81x81 Colour', CONCAT('Description de notre produit ', nom), 3.91, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (84, 'Wine - Bouchard La Vignee Pinot', CONCAT('Description de notre produit ', nom), 1.57, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (85, 'Buffalo - Short Rib Fresh', CONCAT('Description de notre produit ', nom), 3.02, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (86, 'Phyllo Dough', CONCAT('Description de notre produit ', nom), 3.86, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (87, 'Tamarind Paste', CONCAT('Description de notre produit ', nom), 3.77, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (88, 'Buttons', CONCAT('Description de notre produit ', nom), 0.5, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (89, 'Cilantro / Coriander - Fresh', CONCAT('Description de notre produit ', nom), 2.01, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (90, 'Tuna - Bluefin', CONCAT('Description de notre produit ', nom), 2.87, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (91, 'Fudge - Chocolate Fudge', CONCAT('Description de notre produit ', nom), 1.95, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (92, 'Juice - V8 Splash', CONCAT('Description de notre produit ', nom), 2.4, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (93, 'Island Oasis - Magarita Mix', CONCAT('Description de notre produit ', nom), 0.36, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (94, 'Potatoes - Parissienne', CONCAT('Description de notre produit ', nom), 0.74, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (95, 'Arctic Char - Fresh, Whole', CONCAT('Description de notre produit ', nom), 1.83, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (96, 'Pan Grease', CONCAT('Description de notre produit ', nom), 2.0, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (97, 'Eggwhite Frozen', CONCAT('Description de notre produit ', nom), 2.72, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (98, 'Raisin - Dark', CONCAT('Description de notre produit ', nom), 3.88, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (99, 'Compound - Rum', CONCAT('Description de notre produit ', nom), 3.46, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (100, 'Onion Powder', CONCAT('Description de notre produit ', nom), 1.44, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (101, 'Tortillas - Flour, 10', CONCAT('Description de notre produit ', nom), 2.23, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (102, 'Oneshot Automatic Soap System', CONCAT('Description de notre produit ', nom), 2.13, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (103, 'Tea - Decaf 1 Cup', CONCAT('Description de notre produit ', nom), 0.28, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (104, 'Beef - Cow Feet Split', CONCAT('Description de notre produit ', nom), 3.13, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (105, 'Beef - Ground, Extra Lean, Fresh', CONCAT('Description de notre produit ', nom), 2.79, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (106, 'Steampan - Foil', CONCAT('Description de notre produit ', nom), 2.29, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (107, 'Beef - Ground, Extra Lean, Fresh', CONCAT('Description de notre produit ', nom), 2.83, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (108, 'Madeira', CONCAT('Description de notre produit ', nom), 3.84, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (109, 'Cabbage - Green', CONCAT('Description de notre produit ', nom), 1.82, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (110, 'Ranchero - Primerba, Paste', CONCAT('Description de notre produit ', nom), 0.65, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (111, 'Onions - White', CONCAT('Description de notre produit ', nom), 3.44, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (112, 'Table Cloth 62x120 White', CONCAT('Description de notre produit ', nom), 2.63, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (113, 'Nut - Hazelnut, Whole', CONCAT('Description de notre produit ', nom), 0.66, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (114, 'Oil - Truffle, White', CONCAT('Description de notre produit ', nom), 3.24, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (115, 'Pasta - Bauletti, Chicken White', CONCAT('Description de notre produit ', nom), 1.53, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (116, 'Capon - Breast, Wing On', CONCAT('Description de notre produit ', nom), 1.89, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (117, 'Potatoes - Mini White 3 Oz', CONCAT('Description de notre produit ', nom), 3.96, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (118, 'Schnappes - Peach, Walkers', CONCAT('Description de notre produit ', nom), 3.84, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (119, 'Wine - Ruffino Chianti', CONCAT('Description de notre produit ', nom), 0.82, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (120, 'Cheese - Boursin, Garlic / Herbs', CONCAT('Description de notre produit ', nom), 2.85, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (121, 'Muffins - Assorted', CONCAT('Description de notre produit ', nom), 3.02, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (122, 'Pastry - Lemon Danish - Mini', CONCAT('Description de notre produit ', nom), 2.21, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (123, 'Bread - Pullman, Sliced', CONCAT('Description de notre produit ', nom), 0.34, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (124, 'Wine - Cotes Du Rhone', CONCAT('Description de notre produit ', nom), 2.04, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (125, 'Wine - Clavet Saint Emilion', CONCAT('Description de notre produit ', nom), 2.99, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (126, 'Table Cloth 54x54 Colour', CONCAT('Description de notre produit ', nom), 1.03, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (127, 'Sauce - Plum', CONCAT('Description de notre produit ', nom), 3.1, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (128, 'Oil - Cooking Spray', CONCAT('Description de notre produit ', nom), 1.37, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (129, 'Pork - Bacon, Double Smoked', CONCAT('Description de notre produit ', nom), 0.48, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (130, 'Loquat', CONCAT('Description de notre produit ', nom), 1.28, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (131, 'Cheese - Comte', CONCAT('Description de notre produit ', nom), 3.05, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (132, 'Red Snapper - Fillet, Skin On', CONCAT('Description de notre produit ', nom), 2.24, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (133, 'Beans - Kidney, Canned', CONCAT('Description de notre produit ', nom), 1.75, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (134, 'Table Cloth 90x90 Colour', CONCAT('Description de notre produit ', nom), 1.51, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (135, 'Wine - Montecillo Rioja Crianza', CONCAT('Description de notre produit ', nom), 3.89, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (136, 'Muffin Batt - Ban Dream Zero', CONCAT('Description de notre produit ', nom), 1.68, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (137, 'Puree - Kiwi', CONCAT('Description de notre produit ', nom), 1.47, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (138, 'Pork Casing', CONCAT('Description de notre produit ', nom), 3.78, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (139, 'Tomatoes - Yellow Hot House', CONCAT('Description de notre produit ', nom), 3.93, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (140, 'Cream - 18%', CONCAT('Description de notre produit ', nom), 1.19, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (141, 'Nescafe - Frothy French Vanilla', CONCAT('Description de notre produit ', nom), 0.14, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (142, 'Wine - Alicanca Vinho Verde', CONCAT('Description de notre produit ', nom), 3.68, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (143, 'Lettuce - Curly Endive', CONCAT('Description de notre produit ', nom), 3.04, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (144, 'Syrup - Monin, Swiss Choclate', CONCAT('Description de notre produit ', nom), 2.16, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (145, 'Beef - Salted', CONCAT('Description de notre produit ', nom), 1.34, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (146, 'Bread - Multigrain Oval', CONCAT('Description de notre produit ', nom), 1.97, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (147, 'Orange Roughy 6/8 Oz', CONCAT('Description de notre produit ', nom), 3.69, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (148, 'Wine - Ej Gallo Sierra Valley', CONCAT('Description de notre produit ', nom), 2.27, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (149, 'Bandage - Fexible 1x3', CONCAT('Description de notre produit ', nom), 2.95, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (150, 'Iced Tea - Lemon, 460 Ml', CONCAT('Description de notre produit ', nom), 3.74, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (151, 'Wine - White, Pinot Grigio', CONCAT('Description de notre produit ', nom), 4.0, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (152, 'Oil - Sesame', CONCAT('Description de notre produit ', nom), 3.49, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (153, 'Butcher Twine 4r', CONCAT('Description de notre produit ', nom), 1.83, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (154, 'Wine - Guy Sage Touraine', CONCAT('Description de notre produit ', nom), 2.84, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (155, 'Pasta - Rotini, Dry', CONCAT('Description de notre produit ', nom), 3.12, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (156, 'Nut - Hazelnut, Ground, Natural', CONCAT('Description de notre produit ', nom), 3.33, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (157, 'Coconut - Whole', CONCAT('Description de notre produit ', nom), 0.94, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (158, 'Scallops - 10/20', CONCAT('Description de notre produit ', nom), 0.47, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (159, 'Piping - Bags Quizna', CONCAT('Description de notre produit ', nom), 3.32, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (160, 'Carbonated Water - Peach', CONCAT('Description de notre produit ', nom), 2.07, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (161, 'Tea Leaves - Oolong', CONCAT('Description de notre produit ', nom), 3.86, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (162, 'Wine - White, Gewurtzraminer', CONCAT('Description de notre produit ', nom), 0.4, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (163, 'Plasticforkblack', CONCAT('Description de notre produit ', nom), 3.45, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (164, 'Liqueur Banana, Ramazzotti', CONCAT('Description de notre produit ', nom), 1.76, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (165, 'Muffin - Mix - Creme Brule 15l', CONCAT('Description de notre produit ', nom), 2.67, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (166, 'Radish - Black, Winter, Organic', CONCAT('Description de notre produit ', nom), 3.31, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (167, 'Beer - Sleeman Fine Porter', CONCAT('Description de notre produit ', nom), 3.68, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (168, 'Wine - Red, Wolf Blass, Yellow', CONCAT('Description de notre produit ', nom), 0.85, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (169, 'Truffle Cups - White Paper', CONCAT('Description de notre produit ', nom), 0.53, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (170, 'Soy Protein', CONCAT('Description de notre produit ', nom), 3.63, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (171, 'Cattail Hearts', CONCAT('Description de notre produit ', nom), 3.8, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (172, 'Red Currants', CONCAT('Description de notre produit ', nom), 3.79, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (173, 'Icecream - Dstk Super Cone', CONCAT('Description de notre produit ', nom), 3.2, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (174, 'Cabbage - Nappa', CONCAT('Description de notre produit ', nom), 0.45, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (175, 'Wine - Niagara,vqa Reisling', CONCAT('Description de notre produit ', nom), 1.06, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (176, 'Wine - Barbera Alba Doc 2001', CONCAT('Description de notre produit ', nom), 1.4, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (177, 'Appetizer - Escargot Puff', CONCAT('Description de notre produit ', nom), 2.67, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (178, 'Wine - Rosso Toscano Igt', CONCAT('Description de notre produit ', nom), 3.75, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (179, 'Bagel - 12 Grain Preslice', CONCAT('Description de notre produit ', nom), 0.68, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (180, 'Beef - Montreal Smoked Brisket', CONCAT('Description de notre produit ', nom), 2.27, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (181, 'Sour Puss Sour Apple', CONCAT('Description de notre produit ', nom), 2.0, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (182, 'Water Chestnut - Canned', CONCAT('Description de notre produit ', nom), 0.11, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (183, 'Bread - White, Sliced', CONCAT('Description de notre produit ', nom), 3.58, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (184, 'Cilantro / Coriander - Fresh', CONCAT('Description de notre produit ', nom), 0.52, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (185, 'Huck White Towels', CONCAT('Description de notre produit ', nom), 1.76, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (186, 'Wine - Red, Black Opal Shiraz', CONCAT('Description de notre produit ', nom), 0.87, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (187, 'Calaloo', CONCAT('Description de notre produit ', nom), 2.74, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (188, 'Onions - Cooking', CONCAT('Description de notre produit ', nom), 1.88, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (189, 'Beer - Alexander Kieths, Pale Ale', CONCAT('Description de notre produit ', nom), 3.65, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (190, 'Chocolate - Milk, Callets', CONCAT('Description de notre produit ', nom), 1.91, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (191, 'Pasta - Penne, Lisce, Dry', CONCAT('Description de notre produit ', nom), 2.86, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (192, 'Beef - Inside Round', CONCAT('Description de notre produit ', nom), 0.12, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (193, 'Cheese - Perron Cheddar', CONCAT('Description de notre produit ', nom), 1.25, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (194, 'Wine - Beringer Founders Estate', CONCAT('Description de notre produit ', nom), 1.0, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (195, 'Compound - Strawberry', CONCAT('Description de notre produit ', nom), 3.78, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (196, 'Chocolate Bar - Coffee Crisp', CONCAT('Description de notre produit ', nom), 0.42, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (197, 'Rambutan', CONCAT('Description de notre produit ', nom), 3.38, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (198, 'Split Peas - Yellow, Dry', CONCAT('Description de notre produit ', nom), 1.07, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (199, 'V8 Pet', CONCAT('Description de notre produit ', nom), 1.33, 5.5);
INSERT INTO `produits` (`id`, `nom`, `description`, `prix_ht_unitaire`, `tva`) VALUES (200, 'Lentils - Red, Dry', CONCAT('Description de notre produit ', nom), 0.06, 5.5);
